# A functional, but probably terrible, example of GitLab CI for Flutter
image: cirrusci/flutter

variables:
before_script:
  - flutter channel beta
  - flutter upgrade
  - sudo chmod +x /builds/rlazom/BanKDroid/android/gradlew
  - mkdir -p deliverables
  
stages:
  - build
#  - deploy
#  - test

build:
  stage: build
  script:
    - flutter build apk
    - mv build/app/outputs/apk/release/app-release.apk ./deliverables/bankdroid.apk
  artifacts:
    expire_in: 4 weeks
    paths:
    - deliverables  
    
#deploy:
#  stage: deploy
#  script:
#    - mv build/app/outputs/apk/release/app-release.apk ./deliverables/bankdroid.apk
#  artifacts:
#    expire_in: 4 weeks
#    paths:
#    - deliverables


#unitTests:
#  stage: test
#  script:
#    - flutter test test/widget_test.dart